<div id="zip-payment-notice">
    <h3>Zip Payment Notice</h3>
    <p>Latest Version: <?= $this->getVersion() ?></p>
    <?php if(!empty($this->getNews())): ?>
        <ul>
            <?php foreach($this->getNews() as $news): ?>
                <li><?= $news ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>

<style type="text/css">
#zip-payment-notice {
    background: #efefef;
    padding: 10px 25px;
}
</style>