<?php 
    $element = $this->getData('element');
    $groupConfig = $this->getData('config');
?>

<div class="config-heading">
    <div class="heading">
        <strong>
            <?php if(!empty($groupConfig['logo'])): ?>
                <img class="logo" alt="<?= $element->getLegend() ?>" title="<?= $element->getLegend() ?>" src="<?= $groupConfig['logo'] ?>"/>
            <?php endif; ?>
            <?php if(!empty($element->getLegend())): ?>
                <span class="legend"><?= $element->getLegend() ?></span>
            <?php endif; ?>
        </strong>
        <span class="heading-intro">
            <?php if (!empty($element->getComment())): ?>
                <?= $element->getComment() ?>
            <?php endif; ?>
            <?php if (!empty($groupConfig['learn_more_link'])): ?>
                <a class="link-more" href="<?= $groupConfig['learn_more_link'] ?>" target="_blank" title="<?= $this->__('Learn More') ?>"><?= $this->__('Learn More') ?></a>
            <?php endif; ?>
        </span>
    </div>

    <div class="button-container">
        <button type="button" class="button" id="<?= $element->getHtmlId() ?>-head" 
        onclick="toggleSolution.call(this, '<?= $element->getHtmlId() ?>', '<?= $this->getUrl('*/*/state') ?>'); return false;">
            <span class="state-closed"><?= $this->__('Configure') ?></span>
            <span class="state-opened"><?= $this->__('Close') ?></span>
        </button>
    </div>

</div>

<style type="text/css">
.config-heading .heading .logo {
    height: 25px;
    line-height: 40px;
    vertical-align: middle;
    margin: 6px 0px;
}

.config-heading .heading .legend {
    line-height: 40px;
    vertical-align: middle;
    padding-left: 10px;
}
</style>

<script type="text/javascript">
//<![CDATA[

toggleSolution = function(id, url) {
    var doScroll = false;
    Fieldset.toggleCollapse(id, url);
    if ($(this).hasClassName("open")) {
        $$(".with-button button.button").each(function(button) {
            if (button != this && $(button).hasClassName("open")) {
                $(button).click();
                doScroll = true;
            }
        }.bind(this));
    }
    if (doScroll) {
        var pos = Element.cumulativeOffset($(this));
        window.scrollTo(pos[0], pos[1] - 45);
    }
}

//]]>
</script>

