
<div class="page-title">
    <h1><?php echo $this->__('Your order has been approved.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>
  <p><?php echo $this->__('Your order # is: %s.', $this->getOrderId()) ?></p>
  <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
  
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location = '<?php echo $this->getUrl() ?>'"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>