<script type="text/javascript">
    //<![CDATA[
    function check() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){

                if (transport.responseText){
           $("messages").update(transport.responseText);
                }
            }
        });
    }
    //]]>
</script>
 
<?php echo $this->getButtonHtml() ?>