<?php
if (!$this->isActive()) {
    return;
}
?>

<script type="text/javascript">

// Zip widgets configuration
zip_widget_merchantId = '<?php echo $this->escapeHtml($this->getMerchantId()); ?>';
zip_widget_env = '<?php echo $this->escapeHtml($this->getEnvironment()); ?>';
zip_widget_region = '<?php echo $this->escapeHtml($this->getRegion()); ?>';
zip_widget_max_price  = <?php echo $this->escapeHtml($this->getMaxOrderTotal()); ?>;
zip_widget_min_price = <?php echo $this->escapeHtml($this->getMinOrderTotal()); ?>;

<?php foreach ($this->getElementSelectors() as $key => $selector): ?>
    zip_widget_<?php echo $this->escapeHtml($key); ?>="<?php echo $this->escapeHtml($selector); ?>";
<?php endforeach; ?>

</script>

<script type="text/javascript" src="<?php echo $this->escapeUrl($this->getLibScript()); ?>"></script>

<?php if ($this->isDebugModeEnabled()) : ?>
<script type="text/javascript">
    Zip.Widget.config.debug = true;
</script>
<?php endif; ?>
