<?php
$methods = $this->getMethods();
$oneMethod = count($methods) <= 1;

$isCheckedCustomercredit = Mage::getSingleton('checkout/session')->getUseInternalCredit();


?>
<?php if (empty($methods)): ?>
    <dt>
    <?php echo $this->__('No Payment Methods') ?>
    </dt>
    <?php
else:
    foreach ($methods as $_method):
        $_code = $_method->getCode();
        if ($_code == 'zipmoneypayment') {
           
            $quote                =  Mage::getSingleton('checkout/session')->getQuote();
            $shipping_country_id  =  $quote->getShippingAddress()->getCountryId();
            $billing_country_id   =  $quote->getBillingAddress()->getCountryId();

            if((isset($shipping_country_id) && $shipping_country_id != 'AU')  ||  (isset($billing_country_id) &&  $billing_country_id != 'AU' ) )
                continue;

            $zip_title = Mage::getStoreConfig('payment/zipmoney_checkout/title');
            ?>
            <dt>
            <?php if (sizeof($this->getMethods()) > 1): ?>
                <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($zip_title) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked" <?php endif; ?> class="radio" />
            <?php else: ?>
                <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" /></span>
            <?php endif; ?>
            <?php if (Mage::getStoreConfig('payment/zipmoney_checkout/displaylogo') && $icon_path = $_method->getCheckoutIconUrl()): ?>
                <label for="p_method_<?php echo $_code ?>"><img id="payment-method-zipmoney-logo" width="40px" src="<?php echo $this->getSkinUrl($icon_path); ?>" alt="zipMoney - Buy now Pay later!" class="v-middle" /> <?php echo $this->escapeHtml($zip_title) ?></label>
            <?php else: ?>
                <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($zip_title) ?></label>
            <?php endif; ?>
            </dt>
            <dd  style="padding-right:45px;">
                <?php echo $this->getPaymentMethodFormHtml($_method); ?>
            </dd>
            <?php
            continue;
        } elseif($_code=='customercredit') {
		$isPartial = $this->isPartialPayment();
		?>
			<dt>
				<?php if ($isPartial==1) { ?>
					<input id="p_method_<?php echo $_code ?>" value="1" type="checkbox" name="payment[use_internal_credit]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="checkbox customercredit_pass" onclick="creditPayment.switchPMethod('<?php echo $_code ?>');" <?php if ($isCheckedCustomercredit) { ?>checked="checked"<?php } ?> />		
				<?php }
				elseif ($isPartial==-1) { ?>
					<input id="p_method_<?php echo $_code ?>_disabled" disabled="disabled" value="1" type="checkbox" name="payment[use_internal_credit]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="checkbox" />
				<?php }
				elseif ($isPartial==0){ ?> 
					<input id="p_method_<?php echo $_code ?>_disabled" disabled="disabled" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="radio" />
				<?php } else { ?>
					<input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="radio" onclick="creditPayment.switchPMethod('<?php echo $_code ?>')"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> />
				<?php }
				?>
				<label for="p_method_<?php echo $_code ?>">
						<?php echo $this->__($_method->getTitle()); 
						if ($_code=='customercredit' && Mage::helper('customercredit')->isEnabledCodes()) {?>
							(<a href="<?php echo $this->getUrl('customercredit/') ?>" target="_blank"><?php echo Mage::helper('customercredit')->__('Recharge') ?></a>)
						<?php } ?>
				</label>
			</dt>
			<?php if($html = $this->getChildHtml('payment.method.'.$_code)){ ?>
			<dd>
				<?php echo $html; ?>
			</dd>
			<?php } ?>
			<?php } else { ?>
        <dt>
        <?php if (!$oneMethod): ?>
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->escapeHtml($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?> class="radio" />
        <?php else: ?>
            <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                <?php $oneMethod = $_code; ?>
            <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
        </dt>
        <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
            <dd>
                <?php echo $html; ?>
            </dd>
        <?php endif; ?>
		<?php } ?>
        <?php
    endforeach;
endif;
?>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
<?php echo $this->getChildChildHtml('scripts'); ?>
    payment.init();
<?php if (is_string($oneMethod)): ?>
        payment.switchMethod('<?php echo $oneMethod ?>');
<?php endif; ?>
    //]]>
</script>
<script type="text/javascript">
    jQuery(document).ready(function (){
        jQuery('.customercredit_pass').removeAttr('disabled');
    });
</script>