<?php 
    $element = $this->getData('element');
    $groupConfig = $this->getData('config');
?>

<div class="config-heading">
    <div class="heading">
        <span class="heading-title">
            <?php if(!empty($groupConfig['logo'])): ?>
                <img class="logo" alt="<?= $element->getLegend() ?>" title="<?= $element->getLegend() ?>" src="<?= $groupConfig['logo'] ?>"/>
            <?php endif; ?>
            <?php if(!empty($element->getLegend())): ?>
                <strong>
                    <span class="legend"><?= $element->getLegend() ?></span>
                </strong>
            <?php endif; ?>
        </span>
        <span class="heading-intro">
            <?php if (!empty($element->getComment())): ?>
                <?= $element->getComment() ?>
            <?php endif; ?>
        </span>
    </div>

    <div class="button-container">
        <button type="button" class="button" id="<?= $element->getHtmlId() ?>-head" 
        onclick="toggleSolution.call(this, '<?= $element->getHtmlId() ?>', '<?= $this->getUrl('*/*/state') ?>'); return false;">
            <span class="state-closed"><?= $this->__('Configure') ?></span>
            <span class="state-opened"><?= $this->__('Close') ?></span>
        </button>
    </div>

</div>

<style type="text/css">
.zip-payment.enabled .config-heading {
    background-image: none;
}
.zip-payment.enabled .config-heading .heading .heading-title {
    background: url(/skin/adminhtml/default/default/images/icon-enabled.png) no-repeat right center;
    background-position: right center;
    padding: 10px 25px 10px 0;
}
.zip-payment .config-heading .heading a {
    font-size: 12px;
    margin-left: 0;
    color: #4f4f4f;
}
.zip-payment .config-heading .heading .logo {
    height: 25px;
    line-height: 40px;
    vertical-align: middle;
    margin: 6px 0px;
}

.zip-payment .config-heading .heading .legend {
    line-height: 40px;
    vertical-align: middle;
    padding-left: 10px;
    font-size: 14px;
}
.zip-payment .config-heading .heading .heading-intro {
    font-size: 12px;
    line-height: 2em;
}
</style>

<script type="text/javascript">
//<![CDATA[

toggleSolution = function(id, url) {
    var doScroll = false;
    Fieldset.toggleCollapse(id, url);
    if ($(this).hasClassName("open")) {
        $$(".with-button button.button").each(function(button) {
            if (button != this && $(button).hasClassName("open")) {
                $(button).click();
                doScroll = true;
            }
        }.bind(this));
    }
    if (doScroll) {
        var pos = Element.cumulativeOffset($(this));
        window.scrollTo(pos[0], pos[1] - 45);
    }
}

//]]>
</script>

