<?php if($this->isActive()) : ?>
    <script type="text/javascript" src="<?php echo $this->escapeUrl($this->getCheckoutJsLibUrl()); ?>"></script>
    <link rel="stylesheet" href="<?php echo $this->escapeUrl($this->getCheckoutStyleUrl()); ?>"/>

    <script type="text/javascript">
    //<![CDATA[

    Zip = Zip || {};
    Zip.Checkout = Zip.Checkout || {};

    Zip.Checkout.settings = {
        methodCode: '<?php echo $this->escapeHtml($this->getMethodCode()); ?>',
        isRedirect: <?php echo $this->isRedirect() ? 'true' : 'false'; ?>,
        checkoutUrl: '<?php echo $this->escapeUrl($this->getCheckoutUrl()); ?>',
        responseUrl: '<?php echo $this->escapeUrl($this->getResponseUrl()); ?>',
        logLevel: '<?php echo $this->escapeHtml($this->getLogLevel()); ?>'
    };

    //]]>

    </script>

    <?php foreach ($this->getCheckoutScriptList() as $scriptUrl) : ?>
        <script type="text/javascript" src="<?php echo $this->escapeUrl($scriptUrl); ?>"></script>
    <?php endforeach; ?>

<?php endif; ?>
