<?php if($this->isActive()) : ?>

    <script type="text/javascript" src="<?php echo $this->getCheckoutJsLibUrl() ?>"></script>

    <script type="text/javascript">
    //<![CDATA[

    Zip = Zip || {};
    Zip.Checkout = Zip.Checkout || {};

    Zip.Checkout.settings = {
        methodCode: '<?php echo $this->getMethodCode() ?>',
        isRedirect: <?php echo $this->isRedirect() ? 'true' : 'false' ?>,
        checkoutUrl: '<?php echo $this->getCheckoutUrl() ?>',
        responseUrl: '<?php echo $this->getResponseUrl() ?>',
        logLevel: '<?php echo $this->getLogLevel() ?>'
    };

    //]]>

    </script>

    <?php foreach ($this->getCheckoutScriptList() as $scriptUrl) :?>
        <script type="text/javascript" src="<?php echo $scriptUrl ?>"></script>
    <?php endforeach; ?>

<?php endif; ?>
