<?php
    $isActive = $this->isActive();
?>

<?php if($isActive) : ?>

<div id="zip_payment--checkout_overlay">
    <div class="container">
        <div class="zip-spinner">
            <span id="spin1"
                class="spin"></span>
            <span id="spin2"
                class="spin"></span>
            <span id="spin3"
                class="spin"></span>
            <span id="spin4"
                class="spin"></span>
        </div>

        <div>
            <h2><strong>Processing your Zip payment</strong></h2>
            <h3>Please do not refresh or close this page</h3>
        </div>
    </div>
</div>

<?php endif; ?>
