<div>
    <button id="zip-payment-credential-button" onclick="javascript:openModal();" class="scalable" type="button" id="<?= $this->getHtmlId() ?>" data-production-url="<?= $this->getProductionUrl() ?>" data-sandbox-url="<?= $this->getSandboxUrl() ?>">
        <span>
            <span>
                <span><?= $this->escapeHtml($this->getButtonLabel()); ?></span>
            </span>
        </span>
    </button>
</div>

<script type="text/javascript">
//<![CDATA[

openModal = function() {
    var mode = $('payment_settings_environment').value;
    var url = $('zip-payment-credential-button').readAttribute('data-' + mode + '-url');
    window.open(url, 'Zip Payment','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, top=100, width=600, height=400');
    return false;
}

//]]>
</script>

