<div>
    <button id="zip-payment-credential-button" onclick="javascript:openModal();" class="scalable" type="button"
    id="<?php echo $this->getHtmlId(); ?>"
    data-production-url="<?php echo $this->escapeUrl($this->getProductionUrl()); ?>"
    data-sandbox-url="<?php echo $this->escapeUrl($this->getSandboxUrl()); ?>">
        <span>
            <span>
                <span id="zip-payment-credential-button-text"
                data-production-text="<?php echo $this->escapeHtml($this->getProductionText()); ?>"
                data-sandbox-text="<?php echo $this->escapeHtml($this->getSandboxText()); ?>"></span>
            </span>
        </span>
    </button>
</div>

<script type="text/javascript">
//<![CDATA[

openModal = function() {
    var mode = $('payment_zip_payment_settings_environment').value;
    var url = $('zip-payment-credential-button').readAttribute('data-' + mode + '-url');
    window.open(
        url,
        'Zip Payment',
        'toolbar=no, location=no, directories=no, status=no, menubar=no,' +
        'scrollbars=yes, resizable=yes, top=100, width=600, height=400'
    );
    return false;
}

updateText = function() {
    var mode = $('payment_zip_payment_settings_environment').value;
    var text = $('zip-payment-credential-button-text').readAttribute('data-' + mode + '-text');
    $('zip-payment-credential-button-text').update(text);
}

updateText();

Event.observe(window, 'load', function() {
    Element.observe('payment_zip_payment_settings_environment', 'change', updateText);
});

//]]>
</script>

