<div id="zip-payment-healthcheck">

    <span class="<?= $this->getStatus() ?>"><?= $this->getStatus() ?></span>

    <?php if(count($this->getItems()) > 0): ?>
        <ul>
            <?php foreach($this->getItems() as $item): ?>
                <li class="<?= $item['status'] ?>"><?= $item['label'] ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

</div>

<style type="text/css">
#zip-payment-healthcheck span {
    padding: 5px 10px;
    text-transform: uppercase;
    display: inline-block;
    color: white !important;
    font-weight: bold;
    border-radius: .25rem;
}
#zip-payment-healthcheck span.success {
    background-color: #28a745;
}
#zip-payment-healthcheck span.warning {
    background-color: #ffc107;
}
#zip-payment-healthcheck span.error {
    background-color: #dc3545;
}
#zip-payment-healthcheck li {
    line-height: 1.2em;
    border-bottom: solid 1px #e3e3e3;
    padding: 5px 0;
}
#zip-payment-healthcheck li.success {
    color: #155724;
}
#zip-payment-healthcheck li.warning {
    color: #856404;
}
#zip-payment-healthcheck li.error {
    color: #721c24;
}
</style>