<?php 
if (!$this->isActive()) {
    return;
} 
?>

<script type="text/javascript">

// Zip widgets configuration
var zip_configurable_widgets = {};

<?php foreach ($this->getElementSelectors() as $key => $selector): ?>
    zip_configurable_widgets.<?php echo $key ?>="<?php echo $selector ?>";
<?php endforeach; ?>

</script>

<div data-zm-merchant="<?php echo $this->getMerchantId() ?>" data-env="<?php echo $this->getEnvironment()?>"></div>
<script type="text/javascript" src="<?php echo $this->getLibScript() ?>"></script>

<?php if ($this->isDebugModeEnabled()) : ?>
<script type="text/javascript">
    Zip.Widget.config.debug = true;
</script>
<?php endif; ?>
