<?php
    $logo = $this->getLogo();
    $title = $this->getTitle();
    $methodCode = $this->getMethodCode();
?>

<?php if(!empty($logo)): ?>
    <img src="<?= $logo ?>" alt="Zip Payment"/>
<?php endif; ?>

<?php if(!empty($title)): ?>
    <span data-zm-asset="checkouttitle" data-zm-widget="inline"><?= $title ?></span>
<?php endif; ?>


<style type="text/css">
input#p_method_<?= $methodCode ?> {
    height: 30px;
}
input#p_method_<?= $methodCode ?> + label > img {
    height: 36px;
    vertical-align: middle;
    padding: 5px 0;
    display: inline-block;
    line-height: 26px;
    margin-right: 5px;
}
input#p_method_<?= $methodCode ?> + label  > span {
    display: inline-block;
    line-height: 26px;
    padding: 5px 0;
}
</style>
