<script>
//<![CDATA[
Event.observe(window,'load', function() {    
  if(window.$zipCheckout!=undefined){
    window.$zipCheckout.setup({
      checkoutExtension:'Aitoc_Aitcheckout',
      methodCode: 'zipmoneypayment',
      redirect: <?php echo $this->isRedirect(); ?>,    
      baseUrl:'<?php echo Mage::getBaseUrl(); ?>',
      loaderImageUrl:'<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>',
      checkoutUri:'<?php echo $this->getCheckoutUrl(); ?>',
      redirectUrl:'<?php echo $this->getRedirectUrl(); ?>',
    });
  }
});
</script>