<?php
    $logo = $this->getLogo();
    $title = $this->getMethod()->getTitle();
?>

<div id="zip_payment_info">
    <?php if(!empty($logo)): ?>
        <img src="<?= $logo ?>" alt="Zip Payment"/>
    <?php endif; ?>

    <?php if(!empty($title)): ?>
        <span><?= $title ?></span>
    <?php endif; ?>
</div>

<?php if ($specificInfo = $this->getSpecificInformation()):?>
<table>
<?php foreach ($specificInfo as $label => $value):?>
    <tr>
        <td><?php echo $this->escapeHtml($label)?>:</td>
        <td><?php echo nl2br(implode($this->getValueAsArray($value, true), "\n"))?></td>
    </tr>
<?php endforeach; ?>
</table>
<?php endif;?>

<?= $this->getChildHtml() ?>

<style type="text/css">
#zip_payment_info img {
    height: 26px;
    vertical-align: middle;
    padding: 5px 0;
    display: inline-block;
    line-height: 26px;
    margin-right: 5px;
}
#zip_payment_info > span {
    display: inline-block;
    line-height: 26px;
    padding: 5px 0;
}
</style>
