<script>
//<![CDATA[
  if(window.$zipCheckout!=undefined){
    window.$zipCheckout.setup({
      checkoutExtension:'<?php echo $this->getExtensionName();?>',
      redirectAfterPayment:<?php echo (int)$this->getRedirectAfterPayment();?>,
      methodCode: 'zipmoneypayment',
      redirect: <?php echo $this->isRedirect(); ?>,
      loaderImageUrl:'<?php echo $this->getUrl().'skin/frontend/base/default/zipmoney/images/opc-ajax-loader.gif'; ?>',
      checkoutUri:'<?php echo $this->getCheckoutUrl(); ?>',
      redirectUrl:'<?php echo $this->getRedirectUrl(); ?>'
    });
  }
//]]>
</script>