<?php
    $methodCode = $this->getMethodCode();
    $cartTotal = $this->getCartTotal();
    $currency = $this->getQuoteCurrencyCode();
    $repayments = $this->getRepaymentData($currency, $cartTotal);
?>
<div id="payment_form_<?php echo $this->escapeHtml($methodCode); ?>" style="display: none">
    <?php if (empty($repayments)): ?>
    <a href="javascript:void(0)" class="zip-hover" zm-widget="popup" zm-popup-asset="checkoutdialog">Learn more</a>
    <?php else: ?>
    <div class="zip-repayment-block">
    <?php foreach($repayments as $label => $price): ?>
    <div class="zip-repayment-details">
        <div class="repayment-label"><?php echo $this->escapeHtml($label) ?></div>
        <div class="repayment-price"><?php echo Mage::helper('checkout')->formatPrice($price) ?></div>
    </div>
    <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>

<style type="text/css">
#payment_form_<?php echo $this->escapeHtml($methodCode); ?> span,
#payment_form_<?php echo $this->escapeHtml($methodCode); ?> a {
    display: inline-block !important;
}
.zip-repayment-block{
    margin: 5px 10px;
    border: 1px solid #eee;
}
.zip-repayment-details{
    display: flex;
    padding: 5px 10px;
    border-bottom: 1px solid #eee;
}
.zip-repayment-details .repayment-label {
    display: flex;
    flex-grow: 1;
    flex-direction: column;
}
.zip-repayment-details .repayment-price{
    text-align: right;
}
</style>
