<?php
    $status = $this->getOverallStatus();
    $items = $this->getItems();
?>

<div id="zip-payment-healthcheck">

    <?php if(!empty($status)): ?>
        <span class="<?= strtolower($this->getStatusLabel($status)) ?>"><?= $this->getStatusLabel($status) ?></span>
    <?php endif; ?>
    
    <?php if(count($items) > 0): ?>
        <ul>
            <?php foreach ($items as $item): ?>
                <li class="<?= strtolower($this->getStatusLabel($item['status'])) ?>"><?= $item['label'] ?></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>

</div>

<style type="text/css">
#zip-payment-healthcheck span {
    padding: 5px 10px;
    text-transform: uppercase;
    display: inline-block;
    color: white !important;
    font-weight: bold;
    border-radius: .25rem;
}
#zip-payment-healthcheck span.success {
    background-color: #28a745;
}
#zip-payment-healthcheck span.warning {
    background-color: #ffc107;
}
#zip-payment-healthcheck span.error {
    background-color: #bf0606;
}
#zip-payment-healthcheck li {
    line-height: 1.2em;
    border-bottom: dashed 1px #e3e3e3;
    padding: 5px 0;
    font-weight: 600 !important;
}
#zip-payment-healthcheck li.success {
    color: #155724 !important;
}
#zip-payment-healthcheck li.warning {
    color: #856404 !important;
}
#zip-payment-healthcheck li.error {
    color: #bf0606 !important;
}
</style>