<?php if($this->isActive()): ?>

<script type="text/javascript" src="<?= $this->getCheckoutJsLibUrl() ?>"></script>

<script type="text/javascript">
//<![CDATA[

Zip = Zip || {};
Zip.Checkout = Zip.Checkout || {};

Zip.Checkout.settings = {
    'methodCode': '<?= $this->getMethodCode() ?>',
    'isRedirect': <?= $this->isRedirect() ? 'true' : 'false' ?>,
    'checkoutUrl': '<?= $this->getCheckoutUrl() ?>',
    'responseUrl': '<?= $this->getResponseUrl() ?>',
    'logLevel': '<?= $this->getLogLevel() ?>'
};

//]]>

</script>

<script type="text/javascript" src="<?= $this->getCheckoutJs() ?>"></script>
<script type="text/javascript" src="<?= $this->getOnePageCheckoutJs() ?>"></script>

<?php endif; ?>