<?php if(!$this->isRedirect()): ?>

    <!-- Zip Payment Checkout Plugin -->
    <script type="text/javascript" src="<?= $this->getLibScript() ?>"></script>

    <script type="text/javascript">
    //<![CDATA[
    Event.observe(window,'load', function() {   

        if(window.$zipCheckout != undefined){  
            window.$zipCheckout.setup({
                checkoutExtension: '<?= $this->getExtensionName() ?>',
                redirectAfterPayment: <?= $this->getRedirectAfterPayment() ?>,
                methodCode: '<?= $this->getMethodCode() ?>'',
                redirect: '<?= $this->isRedirect() ?>'',
                loaderImageUrl: '<?= $this->getLoaderImageUrl() ?>',
                checkoutUri: '<?= $this->getCheckoutUrl(); ?>',
                redirectUrl: '<?= $this->getRedirectUrl(); ?>'
            });
        }

    });
    //]]>
    </script>

<?php endif; ?>


